#!/usr/bin/env bash

set -e



main() {
  local dotfiles_dir="${HOME}/.dotfiles"
  local public=(greet link unlink remove push)

  if [[ -z $1 ]]; then
    usage
  elif ! [[ ${public[*]} =~ $1 ]]; then
    error "Command not found: $1"
  else
    $1
  fi
}

usage() {
  echo usage here
}

greet() {
  echo "hello, dotfiles!"
}

link() {
  echo "Start linking..."

  if [[ ! -d "${HOME}/.local/bin" ]]; then
    mkdir -p "${HOME}/.local/bin"
  fi

  # link dotfiles
  ln -sf "${HOME}/.dotfiles/dotfiles" "${HOME}/.local/bin"

  # link git files
  ln -sf "${dotfiles_dir}/.gitconfig" "${HOME}"
  ln -sf "${dotfiles_dir}/.gitignore_global" "${HOME}"

  success "Done! You can reload shell now."
}

unlink() {
  echo "Start unlinking..."

  command unlink "${HOME}/.zshrc"

  command unlink "${HOME}/.gitconfig"
  command unlink "${HOME}/.gitignore_global"

  success "Symlinks removed. Type \"dotfiles remove\" to completely remove dotfiles from system."
}

remove() {
  command unlink "${HOME}/.local/bin/dotfiles"
  rm -rf "${dotfiles_dir}"

  echo Hope to see you again...
}

push() {
  cd "${dotfiles_dir}" || return

  git add --all
  commit_message=$(TZ=Asia/Krasnoyarsk date +"dotfiles update: %Y-%m-%d %H:%M:%S")
  git commit -m "${commit_message}"
  git push
}

success() {
  printf "\\033[32mSUCCESS:\\033[0m %s\\n" "$@"
}

error() {
  printf "\\033[31mERROR:\\033[0m %s\\n" "$@" >&2
}

main "$@"
